apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
commonLabels:         
  rhtap/gitops: opepc4c4y-python 
  janus-idp.io/tekton: opepc4c4y-python
  backstage.io/kubernetes-id: opepc4c4y-python
  backstage.io/kubernetes-namespace: rhtap-app 
  app.kubernetes.io/part-of: opepc4c4y-python
resources: 
- application-dev.yaml 
- application-stage.yaml 
- application-prod.yaml  