apiVersion: v1
kind: Service
metadata: 
  labels: 
    app.kubernetes.io/instance: opepc4c4y-python
    app.kubernetes.io/managed-by: kustomize
    app.kubernetes.io/name: opepc4c4y-python 
  name: opepc4c4y-python
spec:
  ports:
  - port: 8081 
    targetPort: 8081 
  selector:
    app.kubernetes.io/instance: opepc4c4y-python 
